/**
 * 任务书 p7 表 1 — 23 项水利指标目录
 *
 * 每项给出: 中文名 / 单位 / 数据来源 / 公式 / 提取函数
 * LLM 引用某指标时, 只需说 "见 INDICATORS[idx].name" 即可.
 */

import type { IndicatorCheck, SchemeFullResult, TaskChecklistItem } from "./types";

/** 23 项指标 (与 说明书.md §8 表完全对应) */
export const INDICATORS: IndicatorCheck[] = [
  { index: 1,  name: "正常高水位",       unit: "m",    source: "任务书 p2 (1) / curves.ts:SCHEMES",
    extractor: (s) => s.Z_zheng },
  { index: 2,  name: "设计洪水位",       unit: "m",    source: "任务书 p13 / flood.ts:flood_routing",
    extractor: (s) => s.Z_design },
  { index: 3,  name: "校核洪水位",       unit: "m",    source: "任务书 p13 / flood.ts:flood_routing",
    extractor: (s) => s.Z_check },
  { index: 4,  name: "死水位",           unit: "m",    source: "任务书 p8 / deadLevel.ts:computeDeadLevel",
    extractor: (s) => s.Z_dead },
  { index: 5,  name: "防洪限制水位",     unit: "m",    source: "任务书 p11 / summary.ts:_compute_xun_level",
    extractor: (s) => s.Z_xun },
  { index: 6,  name: "防洪高水位",       unit: "m",    source: "任务书 p13 / flood.ts",
    extractor: (s) => s.Z_fangshou },
  { index: 7,  name: "总库容",           unit: "亿m³", source: "任务书 p3 / curves.ts:z_to_v",
    extractor: (s) => s.V_total },
  { index: 8,  name: "兴利库容",         unit: "亿m³", source: "任务书 p8 / deadLevel.ts",
    extractor: (s) => s.V_xing },
  { index: 9,  name: "防洪库容",         unit: "亿m³", source: "任务书 p11 / summary.ts",
    extractor: (s) => s.V_fangshou },
  { index: 10, name: "兴利防洪结合库容", unit: "亿m³", source: "任务书 p11 / summary.ts",
    extractor: (s) => s.V_jiehe },
  { index: 11, name: "设计洪水最大泄流量", unit: "m³/s", source: "任务书 p15 / flood.ts",
    extractor: (s) => s.Q_design_max },
  { index: 12, name: "校核洪水最大泄流量", unit: "m³/s", source: "任务书 p15 / flood.ts",
    extractor: (s) => s.Q_check_max },
  { index: 13, name: "保证出力",         unit: "万kW", source: "任务书 p9 / firmPower.ts:findNpForScheme",
    formula: "N_p = K·q·H, K=8.5, Δh=1.0m",
    extractor: (s) => s.Np },
  { index: 14, name: "工作容量",         unit: "万kW", source: "任务书 p10 / installed.ts",
    formula: "N_工 = 3.08·(N_p-10) + 7 + 10",
    extractor: (s) => s.N_ji },
  { index: 15, name: "备用容量",         unit: "万kW", source: "任务书 p10 / curves.ts:RESERVE",
    extractor: (s) => s.N_bei },
  { index: 16, name: "必需容量",         unit: "万kW", source: "任务书 p10 / installed.ts:calcInstalled",
    formula: "N_必 = N_工 + N_备",
    extractor: (s) => s.N_bi },
  { index: 17, name: "重复容量",         unit: "万kW", source: "任务书 p12 / energy.ts:find_repeat_capacity",
    extractor: (s) => s.N_chong },
  { index: 18, name: "重复容量利用小时", unit: "h",    source: "任务书 p12 / energy.ts",
    extractor: (s) => 0 /* h_利 在 energy 内部, 此处不直接抽 */ },
  { index: 19, name: "装机容量",         unit: "万kW", source: "任务书 p10 / installed.ts",
    extractor: (s) => s.N_y },
  { index: 20, name: "多年平均发电量",   unit: "亿度", source: "任务书 p12 / energy.ts:find_repeat_capacity",
    extractor: (s) => s.E_avg },
  { index: 21, name: "库容系数",         unit: "—",    source: "任务书 p13 / summary.ts",
    formula: "β_兴 = V_兴 / W_年",
    extractor: (s) => s.coef_xing },
  { index: 22, name: "调节系数",         unit: "—",    source: "任务书 p13 / summary.ts",
    extractor: (s) => s.coef_tiao },
  { index: 23, name: "径流利用系数",     unit: "—",    source: "任务书 p13 / summary.ts",
    formula: "η = (Q_0 - Q_弃) / Q_0",
    extractor: (s) => s.eta },
];

/** 关键公式速查 (供 system prompt 引用) */
export const FORMULAS = [
  { id: "F-N",  name: "出力公式",       expression: "N = K·q·H / N_SCALE",
    source: "任务书 p9", notes: "K=8.5, Δh=1.0m, N_SCALE=1e4 → 万 kW" },
  { id: "F-Zd", name: "下游水位",       expression: "Z_d = f(q)  (Z_q 曲线, 36 节点)",
    source: "任务书 表 3" },
  { id: "F-Sp", name: "自由溢流",       expression: "Q = 1.77·n·B·H^1.5",
    source: "任务书 p15" },
  { id: "F-Or", name: "中孔出流",       expression: "Q = n·ω·μ·√(2gH), μ=0.99-0.53·a/H",
    source: "任务书 p15" },
  { id: "F-Wa", name: "风浪高",         expression: "Δh = 0.0208·V^1.25·D^(1/3)",
    source: "任务书 p15" },
  { id: "F-Dm", name: "坝顶高程",       expression: "Z_坝 = max(Z_设+Δh_1+0.7, Z_校+Δh_2+0.5)",
    source: "任务书 p15" },
  { id: "F-Ni", name: "装机-峰-工-必",  expression: "N_峰=Np-10; N_工=3.08N_峰+7+10; N_必=N_工+N_备",
    source: "任务书 p10" },
  { id: "F-Cr", name: "资金回收因子",   expression: "CRF = r·(1+r)^n / ((1+r)^n - 1)",
    source: "任务书 p17" },
  { id: "F-An", name: "等额年值",       expression: "(P/A, r, n) = ((1+r)^n - 1) / (r·(1+r)^n)",
    source: "任务书 p17" },
  { id: "F-PV", name: "现值",           expression: "P = F / (1+r)^t",
    source: "任务书 p17" },
];

/** 关键参数清单 (供 system prompt 引用) */
export const KEY_PARAMS = [
  { name: "设计保证率 P",          value: "87.5%",           source: "任务书 p2" },
  { name: "安全泄量 Q_安",         value: "20000 m³/s",      source: "任务书 p2 (6)" },
  { name: "大坝设计标准",          value: "P=0.1% (千年)",    source: "任务书 p2" },
  { name: "大坝校核标准",          value: "P=0.01% (万年)",   source: "任务书 p2" },
  { name: "下游防洪标准",          value: "P=5% (20 年)",     source: "任务书 p2" },
  { name: "折算率 r₀",             value: "0.10",            source: "任务书 p16" },
  { name: "施工期 T_建",           value: "11 年",           source: "任务书 p17" },
  { name: "正常运行期 T_运",       value: "50 年",           source: "任务书 p17" },
  { name: "火电寿命 T_火",         value: "25 年",           source: "任务书 p16" },
  { name: "出力系数 K",            value: "8.5",             source: "任务书 p9" },
  { name: "水头损失 Δh",           value: "1.0 m",           source: "任务书 p9" },
  { name: "航运基荷",              value: "10 万 kW",        source: "任务书 p2 (5)" },
  { name: "船闸用水",              value: "10 m³/s (全年)",   source: "任务书 p3 (6)" },
  { name: "灌溉用水",              value: "35 m³/s (5-9月)", source: "任务书 p3 (7)" },
  { name: "年淤积量",              value: "669 万 m³/年",     source: "任务书 p6 (15)" },
  { name: "50 年淤积",             value: "3.345 亿 m³",      source: "任务书 p6 (15)" },
  { name: "风速 V",                value: "12 m/s",          source: "任务书 p15" },
  { name: "吹程 D",                value: "15 km",           source: "任务书 p15" },
  { name: "安全超高 (设计/校核)",  value: "0.7 / 0.5 m",     source: "任务书 p15" },
];

/** 任务书完成度 (基于审计文件 + 当前 engine 实现状态静态评估) */
export const TASK_CHECKLIST: TaskChecklistItem[] = [
  { id: "T-2.1", title: "原始资料 (流域/径流/曲线)",
    requirement: "流域 83800 km², 31 年径流, Z-V 10 节点, Z-q 36 节点",
    status: "done", evidence: "curves.ts + runoff.ts 内联 DATA.DAT",
  },
  { id: "T-2.2", title: "综合利用参数",
    requirement: "船闸 10, 灌溉 35, 凤滩损失, 50 年淤积 3.345 亿 m³",
    status: "done", evidence: "curves.ts:LOCK_Q, IRRIG_Q, FENGTAN_LOSS, NEW_SEDIMENT_50",
  },
  { id: "T-3.1", title: "死水位选择",
    requirement: "Z_死 = max(Z_1 淤积, Z_2 综合利用, Z_3 极限消落)",
    status: "done", evidence: "deadLevel.ts:computeDeadLevel, ε<1m³/s 收敛",
  },
  { id: "T-3.2", title: "保证出力 Np",
    requirement: "31 年长系列, P=87.5%, 4 年破坏 (12.9%≈12-13%)",
    status: "done", evidence: "firmPower.ts:findNpForScheme",
  },
  { id: "T-3.3", title: "装机容量 N_必",
    requirement: "N_峰=Np-10, N_工=3.08N_峰+7+10, N_必=N_工+N_备",
    status: "done", evidence: "installed.ts:calcInstalled",
    warning: "RESERVE {I:30, II:25, III:20, IV:15} 为本设计取值, 任务书未明示" },
  { id: "T-4.1", title: "调度图 — 防破坏线",
    requirement: "P=87.5% 范围内各年逆时序等出力试算, 蓄水过程线外包",
    status: "partial", evidence: "dispatch.ts:compute_fangpo_line",
    warning: "与老师原表 7-8 月数值偏差 ~230%, 需复核取 max 而非 min" },
  { id: "T-4.2", title: "调度图 — 加大出力辅助线",
    requirement: "Z_it = Z_t + (Z_汛 - Z_t)·i/4, i=1,2,3",
    status: "done", evidence: "plot_dispatch.py:36-39, 公式正确" },
  { id: "T-4.3", title: "调度图 — 防洪调度线",
    requirement: "5-9 月防洪高水位以上强制按 Q_安 控泄",
    status: "partial", evidence: "dispatch.ts:compute_fangpo_line 隐含",
    warning: "建议显式输出防洪调度线函数 + 5-9 月 Z_防高 标注" },
  { id: "T-4.4", title: "防洪限制水位",
    requirement: "取 7 月底/8 月初防破坏线坐标",
    status: "partial", evidence: "summary.ts: build_table Z_xun",
    warning: "4 方案 Z_xun = Z_正 (因 V_兴足够), 物理正确但与典型设计不同, 需说明" },
  { id: "T-5.1", title: "重复容量 h_利",
    requirement: "h_利 ≥ 2500h 才算经济装机",
    status: "partial", evidence: "energy.ts:find_repeat_capacity",
    warning: "h_uses 全负, 需修 simulate_long_series V_prev 初值" },
  { id: "T-5.2", title: "多年平均电能 E",
    requirement: "31 年长系列时历法, 凤滩 E 扣减",
    status: "done", evidence: "energy.ts:simulate_long_series + FENGTAN_LOSS" },
  { id: "T-5.3", title: "径流利用系数 η",
    requirement: "η = (Q_0 - Q_弃) / Q_0",
    status: "done", evidence: "summary.ts:build_table eta 字段" },
  { id: "T-6.1", title: "三标准调洪演算",
    requirement: "P=5%, 0.1%, 0.01% 起调=汛限, 5 级规则",
    status: "done", evidence: "flood.ts:flood_routing, 误差 <0.10 亿 m³" },
  { id: "T-6.2", title: "自由/孔口出流",
    requirement: "Q_溢=1.77nBH^1.5, Q_孔=nωμ√(2gH)",
    status: "done", evidence: "curves.ts:discharge_capacity" },
  { id: "T-6.3", title: "坝顶高程 Z_坝",
    requirement: "Z_坝 = max(Z_设+Δh_1+0.7, Z_校+Δh_2+0.5)",
    status: "done", evidence: "summary.ts:build_table, Δh_1=1.146m" },
  { id: "T-7.1", title: "投资构成 (永久/机电/临时/补偿)",
    requirement: "任务书 表 8-11, 11 年分年比例 INVEST_RATIO",
    status: "done", evidence: "curves.ts:ECON, economic.ts" },
  { id: "T-7.2", title: "替代火电+煤矿",
    requirement: "FIRE_KWH_COST=750, MINE_KWH_COST=0.07, FIRE_SCALE=1.1/1.05",
    status: "done", evidence: "economic.ts, curves.ts" },
  { id: "T-7.3", title: "年运行费 u₁, u₂, u₃",
    requirement: "RUN_FACTOR (2.0/2.0/2.2/2.3), 大修三部分, 补偿提成",
    status: "done", evidence: "economic.ts:get_yearly_running" },
  { id: "T-7.4", title: "防洪效益作负费用",
    requirement: "W_avg×V_防×10, 上限 5000 万元",
    status: "partial", evidence: "economic.ts:compute_fangshou_benefit",
    warning: "上限 5000 万元过于简化, 任务书 p20 要求 5 步法" },
  { id: "T-7.5", title: "现值/等额年值法",
    requirement: "r₀=0.10, T_建=11, T_运=50, T_火=25",
    status: "done", evidence: "economic.ts:present_value_of_cashflow, annuity" },
  { id: "T-7.6", title: "推荐方案",
    requirement: "按年费用最小 + 防洪 + 发电 综合选",
    status: "done", evidence: "推荐方案 II, 年费用 14463 万元最低" },
  { id: "T-8.1", title: "附图 — Z-V / Z-q 曲线",
    requirement: "任务书 图 1, 图 2",
    status: "done", evidence: "figs_scientific/fig_zq_curve.png + app.py 主页 Z-V" },
  { id: "T-8.2", title: "附图 — 4 方案调度图 + 防洪调度线",
    requirement: "防破坏线 + 加大出力辅助线 + 防洪调度线",
    status: "partial", evidence: "figs/dispatch_{I,II,III,IV}.png",
    warning: "防破坏线偏差未修复, 防洪调度线未单独标出" },
];

/**
 * 把 indicators 渲染成一张二维表 (indicator × scheme),
 * 方便 LLM 直接引用数值. 缺失值用 undefined.
 */
export function buildIndicatorTable(
  schemes: SchemeFullResult[],
  indicators: IndicatorCheck[] = INDICATORS,
) {
  return indicators.map((def) => {
    const row: { name: string; unit: string; values: Record<string, number | undefined> } = {
      name: def.name,
      unit: def.unit,
      values: {},
    };
    for (const s of schemes) {
      const v = def.extractor(s);
      row.values[s.scheme] = Number.isFinite(v) ? v : undefined;
    }
    return row;
  });
}
